# Generated by Django 5.1.1 on 2024-10-10 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='topic/topic-images')),
            ],
        ),
        migrations.CreateModel(
            name='TopicMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveBigIntegerField()),
                ('views', models.PositiveBigIntegerField()),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='topic.topic')),
            ],
        ),
    ]
