# Generated by Django 5.1.1 on 2024-10-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmeta',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topicmeta',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
