# Generated by Django 5.1.1 on 2024-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_alter_topicmeta_likes_alter_topicmeta_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=150),
        ),
    ]
