# Generated by Django 5.1.1 on 2024-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
